sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - git clone git@github.com:yscoder/hexo-theme-indigo.git themes/indigo
  - npm run build # generate static files
  - cd public
  - ls
  - git init
  - git add .
  - git commit -m 'update log'
  - git push -f "https://${GITHUB_TOKEN}@github.com/gitbu/ai-front-blog.git" master:gh-pages